### ISSUE TITLE
Reviews and give feedback

### ISSUE THREAD

**Issue by pachicodes** [newrelic-experimental/instrumenting-battlesnake-nodejs#1]
Hello ben, when you have some time can you review this repo and give me some feedback on it?
There are some fields note filled because I am not sure what is the right thing to use there, so all the help you can give is welcomed!

Thank you!

**Comment by hummusonrails** [comment]
@pachicodes - It looks great! I added a PR for you to review, and if it looks good, to merge, that fixes some small typos.

You also need to add an example of the `newrelic.js` file in the repository, and show how you can use dotenv variables to safely use your New Relic License Key, i.e. `process.env.NEW_RELIC_LICENSE_KEY`.

**Comment by pachicodes** [comment]
Thank you @bencgreenberg !
I believe I had added the example you mentioned correctly, but just to be safe can you review it when you have time?
Thank you!
